# Database connection
:connection:
  :adapter: sqlite3
  :database: kiosk.db

# Name the site refers to itself with (on ServiceDesk and as the page titles)
:site_name: Kiosk
:site_title: Kiosk
# Minimum length for ticket descriptions (in characters)
:min_description_length: 15
# Number of users to generate signup keys for
:initial_users: 10

:printer_name: CHANGE ME

# ServiceDesk Plus base URL
:sdp: https://servicedesk.example.com
# API key for ServiceDesk Plus
:sdpToken: CHANGE ME

# Secret token for sessions
:secret: CHANGE ME
