# Database connection
:connection:
  :adapter: sqlite3
  :database: kiosk.db

# Name the site refers to itself with
:site_name: Kiosk
# Number of users to generate signup keys for
:initial_users: 10

# ServiceDesk Plus base URL
:sdp: http://sdp.example.com
# API key for ServiceDesk Plus
:sdpToken: CHANGE ME

# Secret token for sessions
:secret: CHANGE ME
