# Database connection
:connection:
  :adapter: sqlite3
  :database: kiosk.db

# Name the site refers to itself with
:site_name: Kiosk
# Number of users to generate signup keys for
:initial_users: 10

# Secret token for sessions
:secret: CHANGE ME
